/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "clients.baml": "// clients.baml\n\nretry_policy MedicalTranscriptionRetry {\n  max_retries 3\n  strategy {\n    type \"exponential_backoff\"\n    delay_ms 500\n    multiplier 2\n    max_delay_ms 15000\n  }\n}\n\nclient<llm> GoogleGeminiClient {\n  provider \"google-ai\"\n  options {\n    model \"gemini-2.5-flash\"\n    api_key env.GOOGLE_AI_API_KEY\n  }\n  retry_policy MedicalTranscriptionRetry\n}\n",
  "transcription.baml": "// Structured transcription output class\nclass TranscriptionOutput {\n  motivo_consulta string @description(\"Reason for visit / Chief complaint\")\n  enfermedad_actual string @description(\"Current illness or condition\")\n  estado_general string @description(\"Patient's general state/appearance\")\n  diagnosticos string @description(\"Identified diagnoses\")\n  conducta string @description(\"Treatment plan and recommendations\")\n  medicamentos string @description(\"Prescribed medications\")\n}\n\n// Main transcription function - structures audio into medical record fields\nfunction TranscribeAudio(audio_text: string) -> TranscriptionOutput {\n  client GoogleGeminiClient\n  prompt #\"\n    The transcribed audio corresponds to a physician dictating a clinical summary after evaluating the patient.\n\n    Preserve all clinically relevant findings exactly as stated.\n\n    Do not assume that missing information is irrelevant.\n\n    If a finding cannot be clearly assigned to a field, place it in the most appropriate field rather than omitting it.\n\n    Prioritize completeness over summarization.\n    \n    {{ ctx.output_format }}\n    \n    ## Transcribed Audio:\n    \n    {{ audio_text }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}